{
 "title": "Application Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "View-1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"active\"}"
    }
   ]
  },
  {
   "title": "Silenced Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"suppressed\"}"
    }
   ]
  },
  {
   "title": "Alertmanager version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "alertmanager_build_info{instance=\"localhost:9093\", job=\"alert_manager\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Alerts In Alertmanager",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts by state",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{instance=\"localhost:9093\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "The total number of failed notifications.",
     "type": "table",
     "description": "alertmanager_notifications_failed_total",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "alertmanager_notifications_failed_total{instance=\"localhost:9093\", job=\"alert_manager\"}"
      }
     ]
    },
    {
     "title": "Alert Manager silences",
     "type": "table",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 6 },
     "targets": [
      {
       "expr": "alertmanager_silences{instance=\"localhost:9093\", job=\"alert_manager\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Number of instances",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(alertmanager_build_info{instance=\"localhost:9093\", job=\"alert_manager\"})"
      }
     ]
    },
    {
     "title": "Total Number of Attempted Notifications.",
     "type": "bargauge",
     "description": "alertmanager_notifications_total",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (integration) (alertmanager_notifications_total{instance=\"localhost:9093\", job=\"alert_manager\"})",
       "legendFormat": "{{integration}}"
      }
     ]
    },
    {
     "title": "Alertmanager version",
     "type": "table",
     "gridPos": { "h": 3, "w": 11, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "alertmanager_build_info{instance=\"localhost:9093\", job=\"alert_manager\"}"
      }
     ]
    }
   ]
  }
 ]
}