{
 "title": "CPU",
 "tags": [ "ServerMonitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "label": "Server",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$serverName\"},instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "serverName",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">${serverName}</h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "time()" }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "description": "Total time that system was up and running after reboot",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"$Server\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Usage ($interval)",
   "type": "gauge",
   "description": "Removing the idle time percentage from 100 will give you the CPU utilization percentage  (Stat Graph)",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  {
   "title": "CPU Utilzation($interval)",
   "type": "timeseries",
   "description": "Removing the idle time percentage from 100 will give you the CPU utilization percentage (Time series Graph)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  {
   "title": "CPU - Cores",
   "type": "stat",
   "description": "No.of logical cores",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode='system', instance=\"$Server\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU - User Mode($interval)",
   "type": "gauge",
   "description": "Amount of time the cpu spent on user applications",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_cpu_seconds_total{mode=\"user\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU - Idle Mode($interval)",
   "type": "gauge",
   "description": "Amount of time the CPU spent/ stayed idle ",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU - System Mode($interval)",
   "type": "gauge",
   "description": "Amount of time the CPU spent on Kernal related tasks",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_cpu_seconds_total{mode=\"system\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU - IO Wait Mode ($interval)",
   "type": "gauge",
   "description": "iowait is time that the processor/processors are waiting",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_cpu_seconds_total{mode=\"iowait\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Modes ($interval)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"system\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"user\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\".*irq\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Modes ($interval)",
   "type": "timeseries",
   "description": "All CPU modes (Time series )",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"system\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"user\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\".*irq\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Usage, Memory Usage, Disk Usage ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "CPU "
    },
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{instance=\"$Server\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} * 100)",
     "legendFormat": "Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"} * 100) /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Loads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu -load1m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "cpu -load1m"
      }
     ]
    },
    {
     "title": "cpu -load5",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "cpu -load5"
      }
     ]
    },
    {
     "title": "Load15m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "targets": [
      {
       "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "Load15m"
      }
     ]
    },
    {
     "title": "cpu -load1m",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "cpu -load1m"
      }
     ]
    },
    {
     "title": "cpu -load5",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "cpu -load5"
      }
     ]
    },
    {
     "title": "Load15m",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load15{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "Load15m"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "1m load average"
      },
      {
       "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "5m load average"
      },
      {
       "expr": "node_load15{instance=\"$Server\", job=\"$job\"}",
       "legendFormat": "15m load average"
      },
      {
       "expr": "count(node_cpu_seconds_total{instance=\"$Server\",job=\"$job\",mode=\"idle\"})",
       "legendFormat": "logical cores"
      }
     ]
    },
    {
     "title": "cpu -load1m",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "cpu -load1m"
      }
     ]
    },
    {
     "title": "cpu -load5",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "cpu -load5"
      }
     ]
    },
    {
     "title": "Load15m",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load15{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "Load15m"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "status-history",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "1m load average"
      },
      {
       "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
       "legendFormat": "5m load average"
      },
      {
       "expr": "node_load15{instance=\"$Server\", job=\"$job\"}",
       "legendFormat": "15m load average"
      },
      {
       "expr": "count(node_cpu_seconds_total{instance=\"$Server\",job=\"$job\",mode=\"idle\"})",
       "legendFormat": "logical cores"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$Server\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$Server\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Saturation (Drops Receive/Transmit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 11, "y": 44 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{instance=\"DevServer:9100\", job=\"node\"}",
       "legendFormat": "Receive"
      },
      {
       "expr": "node_network_transmit_bytes_total{instance=\"DevServer:9100\", job=\"node\"}",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Devices ",
     "type": "stat",
     "description": "ip a",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(node_network_info)" }
     ]
    },
    {
     "title": "Network Traffic (Receive)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$Server\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Receive"
      }
     ]
    },
    {
     "title": "Network Traffic (Transmit)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$Server\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "cpu usage per process",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rate(process_cpu_seconds_total[$__rate_interval])) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu: 5m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[5m])) * 100)",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "cpu: 10m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 65 },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[10m])) * 100)",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "cpu: 15m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 65 },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[15m])) * 100)",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "CPU Usage Per process",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CPU Usage ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
       "legendFormat": "cpu utilization"
      }
     ]
    },
    {
     "title": "CPU Usage (cores)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{ mode=~\"idle|iowait|steal\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})\n)\n",
       "legendFormat": "core - {{cpu}} "
      }
     ]
    }
   ]
  }
 ]
}