{
 "title": "Disk",
 "description": "https://opensource.com/life/16/10/introduction-linux-filesystems",
 "tags": [ "ServerMonitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$serverName\"},instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "serverName",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">${serverName}</h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "time()" }
   ]
  },
  { "title": "Newer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "File System Space Total Available",
   "type": "stat",
   "description": "This includes all the available file system space in the system includes root (/) and other directories",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "repeat": "serverName",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"$Server\",job=\"$job\"})",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "description": "Gives the root Disk Space given to the system",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "description": "Gives the amount of Disk Used by the machine",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} - node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Disk Available (Root directory)",
   "type": "stat",
   "description": "https://www.geeksforgeeks.org/linux-file-hierarchy-structure/\n- This gives the amount of disk space available in the root directory\n\nThis only shows the root directory available space.This includes /bin, /boot, /dev, /etc, /home, /lib, /media etc",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "timeseries",
   "description": "Based on the root (/) directory, dividing the available space with total space gives the total amount of available in percentage by multiply with 100. \n- By removing the available percentage from 100 will give you the utilized percentage.",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"} * 100)\n /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "Disk space Utilization"
    }
   ]
  },
  { "title": "old", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Filesystem Space Used",
   "type": "timeseries",
   "description": "Filesystem used space.\n> If is > 80% then is Critical.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes) * 100",
     "legendFormat": "Filesystem Space Used: {{alias}} [{{fstype}}] ({{device}}) {{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Usage Per process",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "cpu spent time",
   "type": "timeseries",
   "description": "Number of seconds CPU spent \nrunning a process.",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " node_schedstat_running_seconds_total",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "File System Space Available",
   "type": "table",
   "description": "https://opensource.com/life/16/10/introduction-linux-filesystems",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs'}"
    },
    { "expr": "node_uname_info - 0" }
   ]
  },
  {
   "title": "File System Space Available",
   "type": "timeseries",
   "description": "Mount Points are directories.\ntmpfs (short for Temporary File System) is a temporary file storage paradigm implemented in many Unix-like operating systems. It is intended to appear as a mounted file system, but data is stored in volatile memory instead of a persistent storage device.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "repeat": "serverName",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$Server\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} : {{fstype}}- Available"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "gauge",
   "description": "The weighted # of seconds spent doing I/Os.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"DevServer:9100\", job=\"node\"}[5m]) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"} * 100)\n /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "File System Space Available",
   "type": "piechart",
   "description": "https://www.learnitguide.net/2016/05/disk-management-in-linux-basic-concepts.html.\nGives the amount of space available in the different directories of given machine",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$Server\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  },
  { "title": "DISK  ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Disk IO Saturation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"DevServer:9100\", job=\"node\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Free Space for Each partiton",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"$Server\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "Available Space"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", instance=\"$Server\", job=\"$job\"} * 100) /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",  instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "Utilized Space (%)"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "File System Space Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$Server\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  }
 ]
}