{
 "title": "IO",
 "tags": [ "ServerMonitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$serverName\"},instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "serverName",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">${serverName}</h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "time()" }
   ]
  },
  {
   "title": "Disk I/O Utilisation (%)",
   "type": "timeseries",
   "description": "gives the amount of time spent on io task",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device!~\"^(md\\\\\\\\d+$|dm-)\"}[$interval])",
     "legendFormat": "Disk I/O Utilisation:  {{alias}} [{{device}}]"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os (duplicate)",
   "type": "timeseries",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"DevServer:9100\"}[$interval])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk IO read and write time",
   "type": "timeseries",
   "description": "Read time ms Number of seconds per disk partition read operation\n\nWrite time ms Number of seconds spent per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\n IO time weighted Weighted seconds spent per disk partition input/output operation",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Read Write Bytes/sec",
   "type": "timeseries",
   "description": "Gives the amount of disk read and write in bytes",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "$serverName-Read Bytes"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "$serverName-Write bytes"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Usage ($interval)",
     "type": "gauge",
     "description": "Metric gives no.of seconds time spent doing i/o\n\nhttps://devconnected.com/monitoring-disk-i-o-on-linux-with-the-node-exporter/",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=\"$Server\", job=\"$job\", device=\"sda\"}[$interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "IO Utilization($interval)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=\"$Server\", job=\"$job\", device=\"sda\"}[$interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write($interval)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{job=\"$job\", instance=\"$Server\"}[$interval])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{job=\"$job\", instance=\"$Server\"}[$interval])",
       "legendFormat": "{{device}} - Successfully write bytes"
      }
     ]
    },
    {
     "title": "Disk read and write rate（IOPS）",
     "type": "timeseries",
     "description": "Reads completed: Reads per second per disk partition\n\nWrites completed: Number of writes per second per disk partition\n\nIO now Number of input/output requests being processed per disk partition per second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total[1m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total[1m])",
       "legendFormat": "{{device}}_write"
      },
      { "expr": "node_disk_io_now", "legendFormat": "{{device}}" }
     ]
    },
    {
     "title": "Disk I/O utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{job=\"node\"}[5m]) / 1000",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}