{
 "title": "Prometheus Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "time()" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": {
    "content": "<img src=\"https://cdn.worldvectorlogo.com/logos/prometheus.svg\"/ height=\"140px\">"
   }
  },
  {
   "title": "Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=\"prometheus\",instance=\"localhost:9090\"})"
    }
   ]
  },
  {
   "title": "Alertmanager Count",
   "type": "gauge",
   "description": "count of number of alertmanagers cofigured in prometheus yaml file",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered{instance=\"localhost:9090\", job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "description": "shows the active and inactive targets",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Currently Down",
   "type": "stat",
   "description": "Servers which are DOWN RIGHT NOW! \nFIX THEM!!",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up == 0" }
   ]
  },
  {
   "title": "Prometheus Version",
   "type": "stat",
   "description": "Gives the version of prometheus instance",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"localhost:9090\", job=\"prometheus\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Samples Appended",
   "type": "timeseries",
   "description": "lowest level of keeping metrics is samples, these samples added and made into timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{instance=\"localhost:9090\", job=\"prometheus\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "description": "Amount of time spent to scrape the metrics from respective targets",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of time series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_head_series)"
    }
   ]
  },
  {
   "title": "Prometheus alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": " sum (ALERTS)", "legendFormat": "firing alerts" }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "timeseries",
   "description": "Each two-hour block consists of a directory containing a chunks sub directory containing all the time series samples for that window of time, a metadata file, and an index file.\nsamples - chunks - blocks ",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 26 },
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{instance=\"localhost:9090\", job=\"prometheus\"}",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Application Status",
   "type": "table",
   "description": "Gives which target application is active and inactive",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}