{
 "title": "Servers Overview",
 "tags": [ "ServerStatus" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": "DevServer:9100, DevServer:9200" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Resource Overview",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)"
    },
    {
     "expr": "node_load5{job=~\"$job\"}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[2m])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100"
    },
    {
     "expr": "max((node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[2m])) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[2m])) by (instance)"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\"} - 0"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[2m])*8) by (instance)"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[2m])*8) by (instance)"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=\"$job\"} * 100)\n /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Disk Details ($node)",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    },
    {
     "expr": "node_uname_info{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU/Memory Usage ($node)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$__rate_interval])) * 100",
     "legendFormat": "CPU IO"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "RAM Used {{instance}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "Used SWAP {{instance}}"
    }
   ]
  }
 ]
}