{
 "title": "LQR Report",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "S_BcnId",
    "query": "select s_bcnid from f_ue_common_id where ueid='$mc'"
   },
   {
    "name": "Date",
    "query": "Select to_char(reg_time,'YYYY-MM-DD') from f_ue_registration"
   },
   {
    "name": "mc",
    "query": "select ueid from f_ue_common_id"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  \n  ueid\nFROM f_ue_common_id\nWHERE s_bcnid= $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  s.evt_time AS \"time\",\n  s.s_bcnid\nFROM f_ue_common_id s\nWHERE s.s_bcnid= $S_BcnId\nAND s.ueid='$mc'\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  reg_time AS \"time\",\n  to_char(reg_time,'yyyy-mm-dd hh24:mi:ss:ms') AS REG_TIME\n  FROM f_ue_registration\nWHERE s_bcnid= $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  reg_time AS \"time\",\n  to_char(evt_time AT TIME ZONE 'Asia/Kolkata','yyyy-mm-dd hh24:mi:ss:ms') AS deREG_TIME\n  FROM f_ue_deregistration\nWHERE s_bcnid= $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  reg_time AS \"time\",\n  (select count(*) from lqr l where l.s_bcnid=$S_BcnId) as LQR_COUNT\n  FROM f_ue_deregistration\nWHERE s_bcnid= $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PayLoadBytesReceived-original",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  payloadbytesreceived\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid = $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PayLoadBytesSent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  payloadbytessent\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid = $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NumOf UE LQRs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  numofuelqrs\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "No Of UPlink BCN PDU's Discarded",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  discardulpdudownlink\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Maxpimum EIRP Detected (maxUEEIRPmeas)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  maxueeirpmeas\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UetimingOffsMin",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  uetimingoffsmin\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SREJ Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  srejsent\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Downlink PDU Discarded (BCN Layer)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  discardbcnpduuplink\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Minimum EIRP Detected (minUEEIRPmeas)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  minueeirpmeas\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SREJ Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  srejreceived\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UetimingOffsMax",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  uetimingoffsmax\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UETimingoffSave",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  uetimingoffsmax\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UE Signal To Noise Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  minuerecsnr\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  maxuerecsnr\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "IMSI ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  ueid\nFROM f_ue_common_id\nWHERE s_bcnid= $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "S_BCNID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  s.evt_time AS \"time\",\n  s.s_bcnid\nFROM f_ue_common_id s\nWHERE s.s_bcnid= $S_BcnId\nAND s.ueid='$mc'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "REG_TIME",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  reg_time AS \"time\",\n  to_char(reg_time,'yyyy-mm-dd hh24:mi:ss:ms') AS REG_TIME\n  FROM f_ue_registration\nWHERE s_bcnid= $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DEREG_TIME",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  reg_time AS \"time\",\n  to_char(evt_time AT TIME ZONE 'Asia/Kolkata','yyyy-mm-dd hh24:mi:ss:ms') AS deREG_TIME\n  FROM f_ue_deregistration\nWHERE s_bcnid= $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PayLoadBytesReceived",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  payloadbytesreceived\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid = $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PayLoadBytesSent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  payloadbytessent\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid = $S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SREJ Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  srejreceived\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SREJ Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  srejsent\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UE Signal To Noise Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  minuerecsnr\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  maxuerecsnr\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NumOf UE LQRs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  numofuelqrs\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "No Of UPlink BCN PDU's Discarded",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  discardulpdudownlink\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Maxpimum EIRP Detected (maxUEEIRPmeas)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  maxueeirpmeas\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Minimum EIRP Detected (minUEEIRPmeas)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  minueeirpmeas\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Downlink PDU Discarded (BCN Layer)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  discardbcnpduuplink\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UetimingOffsMax",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  uetimingoffsmax\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UETimingoffSave",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  uetimingoffsmax\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UetimingOffsMin",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  uetimingoffsmin\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\n  and s_bcnid=$S_BcnId\nORDER BY 1"
    }
   ]
  }
 ]
}