{
 "title": "RNS Overall Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "f_ue_deregistration",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  f_ue_deregistration.*\nFROM f_ue_deregistration\nWHERE\n  $__timeFilter(evt_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "f_ue_registration",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  reg_time AS \"time\",\n  f_ue_registration.*\nFROM f_ue_registration\nWHERE\n  $__timeFilter(reg_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "f_ue_common_id",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  reg_time AS \"time\",\n  f_ue_common_id.*\nFROM f_ue_common_id\nWHERE\n  $__timeFilter(reg_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LQR",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  evt_time AS \"time\",\n  lqr.*\nFROM lqr\nWHERE\n  $__timeFilter(evt_time)\nORDER BY 1"
    }
   ]
  }
 ]
}